brew "git"
brew "bat"
# brew "deno"
brew "tree"
brew "zsh-syntax-highlighting"
# brew "jump"
brew "bat"
brew "tree"
brew "zsh-autosuggestions"
brew "git-gui"
brew "neovim"
brew "tokei"

# cask "iterm2"
# cask "rectangle"
# cask "visual-studio-code"
# cask "flycut"
# cask "arc"
